# ==========================================================
#  LessLag Configuration File
#  This plugin helps reduce server and client lag by using
#  various performance optimizations. Each section below
#  can be enabled or disabled and customized.
# ==========================================================

# Permissions:
# - lesslag.admin (main permission for using the lesslag command and features)

settings:
  # Prefix for all chat messages sent by the plugin
  prefix: "§7[§cLessLag§7] §r"
  # How often (in ticks) the plugin checks server TPS.
  # 20 ticks = 1 second
  tps_check_interval: 20
  
  # When TPS drops below this number, certain lag-prevention
  # features will start activating.
  low_tps_threshold: 15.0
  
  # Critical TPS value; if the server goes this low,
  # emergency optimizations (like unloading worlds) may trigger.
  critical_tps_threshold: 10.0

world_management:
  auto_unload:
    enabled: true
    # Wether to save worlds before unloading them
    save_world: true
    # Minutes of no players in a world before it gets unloaded
    inactivity_minutes: 5
    # Worlds that should never be auto-unloaded
    excluded_worlds:
      - world
      - lobby

  force_unload_on_low_tps:
    enabled: true
    # When TPS is critically low, worlds with few/no players will
    # unload automatically, and remaining players will be moved here:
    player_transfer_world: world

item_management:
  auto_clear_drops:
    enabled: true
    # How often (in seconds) all dropped items are cleared
    interval_seconds: 240
    # Items that will never be removed automatically
    whitelist:
      - diamond
      - nether_star

  item_stacking:
    enabled: true
    # Items dropped close to each other (within this radius) merge
    stack_radius: 3.0
    # Hologram text shown above stacked items.
    # Placeholders:
    #   {item_type}   = Type of the item (e.g., "Diamond")
    #   {item_name}   = Name of the item (e.g., "OP Sword") (this is the same as {item_type} but shows the custom name of an item if it got renamed)
    #   {amount} = Total amount in this stack
    hologram_format: "§e{item_name}§f x{amount}"
    # "partial" = pick up only what fits in inventory
    # "full" = pick up entire stack or nothing
    pickup_behavior: "partial"

entity_management:
  # Max number of entities allowed per chunk
  max_entities_per_chunk: 50
  # Max number of entities allowed in an entire world
  max_entities_per_world: 5000
  # If the max is reached, natural mob spawning stops
  disable_natural_spawn_on_limit: true
  # Kill new entities that appear above the limit
  kill_excess_entities: true

  smart_entity_removal:
    # Uses advanced logic to kill the most frequent entity type if overpopulated
    enabled: true
    # Entities that never get killed even if overpopulated
    whitelist:
    - villager
    - wolf
    - item

player_management:
  # Prevents more players from joining or entering a world if it's full
  max_players_per_world: 50
  # The world, players get teleported in, when the max player limit in a world is exceeded (the world player limit is ignored in the fallback world)
  fallback_world: world

  packet_spam_protection:
    enabled: true
    # Number of packets a player can send per second before being punished
    packet_limit: 1000
    # What to do if a player exceeds the limit: "kick" or "ban"
    action: "kick"
    # Reason for the kick/ban that gets displayed to the player when getting kicked/banned
    action_reason: "§cYou're sending way too many packets! Trying to crash the server!?"

  chat_spam_protection:
    enabled: true
    # If more than this amount of messages are sent in total, the chat gets temporarily muted for everyone (except players with permission lesslag.admin)
    max_messages_per_second: 6
    # If chat is spammed heavily, it will be disabled for everyone temporarily
    mute_duration_seconds: 5

performance_controls:
  disable_redstone:
    enabled: true
    # If true, only redstone clocks are disabled
    # (fast-repeating circuits that cause lag)
    clocks_only: true
    # TPS threshold below which redstone is automatically disabled
    disable_below_tps: 12.0 # set this value to >20 to always disable it (same thing for all other disable_below_tps options)

  disable_falling_blocks:
    enabled: true
    # Prevents blocks like sand or gravel from turning into falling blocks
    disable_below_tps: 12.0

  disable_fluids:
    enabled: true
    # Stops water and lava from flowing or being updated
    disable_below_tps: 12.0

  disable_explosions:
    enabled: true
    # Prevents TNT, creeper, or other explosions during heavy lag
    disable_below_tps: 10.0

  disable_ender_pearls:
    enabled: true
    # Stops players from using ender pearls when TPS is low
    disable_below_tps: 10.0

  disable_command_blocks:
    enabled: true
    # Command blocks won't run if TPS are below this threshold
    disable_below_tps: 10.0

  decrease_tickspeed:
    enabled: true
    # The random tickspeed in all worlds will be decreased if TPS are below this threshold
    decrease_below_tps: 15.0
    # The value which the random tickspeed will be changed to (vanilla: 3, most performant: 0)
    decrease_to: 0

mob_ai:
  disable_ai_when_no_players_nearby:
    enabled: false
    # Distance around mobs (in blocks) to check for nearby players
    # If no players are within this radius, mobs will freeze and stop pathfinding
    radius: 32
    # Whether mobs shouldn't take damage while their AI is disabled (recommended, otherwise players could abuse this feature and go far away from mobs and kill them with a ranged weapon)
    invulnerable: true

chunk_loading:
  throttle_on_fast_player_movement:
    enabled: false
    # If a player moves very fast and loads too many chunks
    # while TPS is dropping, chunk loading will be disabled
    # for this amount of seconds to let the server recover
    disable_duration_seconds: 5
    # Total maximum amount of chunks that can be loaded per second on the server (not per player)
    max_chunks_per_second: 500

profiler:
  enabled: true
  # How often the profiler updates (in ticks)
  update_interval_ticks: 20
  # Show CPU usage in profiler
  show_cpu_usage: true
  # Show RAM usage in profiler
  show_ram_usage: true
  # Show number of packets sent and received in profiler
  show_packets: true

web_interface:
  enabled: true

  # Where the web interface for lag detection reports and profiler should be hosted and on which port
  host: "0.0.0.0"
  port: 25580

  authentication:
    # Whether the web interface should be secured with a password and user (recommended)
    enabled: false

    username: admin
    password: 123

  ssl:
    # Whether secure sockets layer should be enabled
    enabled: false

  # Time until a web interface session is suspended
  session_timeout_minutes: 60

  # Generate and send access links to the player in the chat when a web interface session is started via in game commands
  generate_access_links: true

  # Time until an access link is no longer usable
  access_link_expiration_minutes: 30

# Command: /lesslag web reports
lag_reports:
  enabled: true

  # Conditions for a lag report to be generated
  trigger:
    tps_below: 15.0

    duration_seconds: 15

  # Time after a lag report in which no new lag report can be generated
  cooldown_minutes: 10

  # How to notify admins when a lag report is generated
  notifications:
    chat_message: true
    action_bar: false

    permission: lesslag.admin

  # Save lag reports to a database
  storage:
    save_reports: true

    # Time until a lag report is deleted (in days)
    retention_days: 180

  # Which metrics to analyze as a possible lag cause
  analysis:
    entity_count: true
    dropped_items: true
    chunk_loads: true
    plugin_tasks: true
    villagers: true
    hoppers: true
    redstone: true
    loaded_worlds_count: true
    recent_player_commands: true # amount and full commands + player names (useful for abused exploits)

explosion_queue:
  enabled: true

  # Maximum explosions processed each tick
  explosions_per_tick: 5

  # Whether to use dynamic scaling based on TPS (low TPS = lower explosions per tick, vice versa)
  dynamic_scaling: true

  # Only queue explosions when TPS are low
  low_tps_only:
    enabled: false

    tps_below: 15.0

  # Which explosions to queue
  queue_types:
    tnt: true
    creeper: true
    end_crystal: false
    bed: true
    respawn_anchor: true
    ghast_fireball: false
    wither_skull: false

  # Worlds in which explosions shouldn't be queued
  bypass_worlds:
    - pvp_world
    - practice

  limits:
    # Maximum explosions in queue
    max_queue_size: 500

    # Whether new explosions shouldn't be processed at all when the queue is full
    cancel_new_explosions_when_full: true

# Command: /lesslag web profiler
task_profiler:
  # Whether the task profiler, showing live bukkit and plugin tasks, should be enabled/usable
  enabled: true

  sampling:
    # Interval between tasks being re-checked and displayed
    interval_ticks: 1

  # Which tasks to track
  tracking:
    sync_tasks: true
    async_tasks: true

  data:
    retain_sessions: 25

  alerts:
    enabled: true

    # Amount of MSPT per plugin before notifying admins (lesslag.admin)
    # If a plugin exceeds this threshold, admins will be notified while the task profiler is running
    warning_ms_per_tick: 5.0

# Command: /lesslag web history
performance_history:
  enabled: true

  # How often performance metrics are collected
  collection_interval_minutes: 2

  # Number of days to keep historical data
  retention_days: 180

  # This is where performance data is saved
  database:
    type: sqlite
    file: performance.db

  # Which metrics to collect and save
  metrics:
    tps: true
    mspt: true
    cpu_usage: true
    ram_usage: true
    online_players: true
    loaded_chunks: true
    loaded_entities: true
    dropped_items: true
    villager_count: true
    mob_count: true